---
- name: Set map fact
  ansible.builtin.set_fact:
    helm_map:
      directory:
        share: /usr/local/share/helm
      release:
        channel: '{{ helm_vars.release.repository.url }}/{{ helm_vars.release.repository.channel }}'
        key: '{{ helm_vars.release.repository.url }}/{{ helm_vars.release.repository.key }}'
        url: '{{ helm_vars.release.distro.url }}/{{ helm_vars.release.repository.channel }}/{{ helm_vars.release.distro.name }}'
        version: '{{ helm_vars.release.version[1:] }}'
  run_once: true

- name: Set project fact
  ansible.builtin.set_fact:
    helm_project:
      environment:
        HELM_CACHE_HOME: '{{ helm_map.directory.share }}/cache'
        HELM_CONFIG_HOME: '{{ helm_map.directory.share }}/config'
        HELM_DATA_HOME: '{{ helm_map.directory.share }}'
        HELM_PLUGINS: '{{ helm_map.directory.share }}/plugins'
        HELM_REGISTRY_CONFIG: '{{ helm_map.directory.share }}/config/registry/config.json'
        HELM_REPOSITORY_CACHE: '{{ helm_map.directory.share }}/cache/repository'
        HELM_REPOSITORY_CONFIG: '{{ helm_map.directory.share }}/config/repositories.yaml'
      release:
        package: '{{ helm_map.release.url }}/packages/helm/releases/{{ helm_map.release.version }}'
  run_once: true

- name: Set plugin packages fact
  ansible.builtin.set_fact:
    helm_plugin_packages: '{{ plugin.packages }}'
  loop: '{{ helm_vars.plugins }}'
  loop_control:
    loop_var: plugin
  run_once: true
  when:
    - plugin.enabled is truthy
    - plugin.packages is defined

- name: Set plugin packages disabled fact
  ansible.builtin.set_fact:
    helm_plugin_packages_disabled: '{{ plugin.packages }}'
  loop: '{{ helm_vars.plugins }}'
  loop_control:
    loop_var: plugin
  run_once: true
  when:
    - plugin.enabled is falsy
    - plugin.packages is defined
