---
repos:
  - repo: https://github.com/theepicsaxguy/k3s-cluster
    rev: v1.0.0
    hooks:
      - id: argo-cd
      - id: cert-manager
      - id: cilium
      - id: cluster
      - id: coredns
      - id: external-dns
      - id: helm
      - id: k3s
      - id: kured
      - id: longhorn
      - id: metrics-server
      - id: victoria-logs-single
      - id: victoria-metrics-k8s-stack
    args: ["--chart-search-root=./roles"]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        name: YAML Linter
        types: [yaml]
        args:
          [
            "-d",
            "{extends: default, rules: {line-length: {max: 120}, indent: {spaces: 2}}}",
          ]

  - repo: https://github.com/prettier/prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: Prettier (YAML auto-fix)
        types: [yaml]
        args: ["--write"]

  - repo: https://github.com/ansible/ansible-lint
    rev: v5.0.0
    hooks:
      - id: ansible-lint
        name: Ansible Linter
        types: [yaml]

  - repo: https://github.com/instrumenta/helm-lint
    rev: v1.0.0
    hooks:
      - id: helm-lint
        name: Helm Linter
        args: ["--strict"]

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0
    hooks:
      - id: helm-docs
        name: Helm Docs Generator
        args: ["--chart-search-root=./roles"]
