---
- name: Cluster Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - cluster
  tags: cluster

- name: LoadBalancer Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  tags:
    - cluster
    - kubernetes
  tasks:
    - name: Setup loadbalancer
      ansible.builtin.import_role:
        name: k3s
        tasks_from: loadbalancer

- name: Kubernetes Provisioning
  hosts: cluster
  become: true
  gather_facts: true
  roles:
    - helm
    - k3s
  serial:
    - 1
    - 2
    - 3
  tags: kubernetes

- name: Charts Provisioning
  hosts: server
  become: true
  gather_facts: true
  post_tasks:
    - name: Perform post-install tasks
      ansible.builtin.include_role:
        name: '{{ postinstall }}'
        tasks_from: postinstall
      loop:
        - argo-cd
        - cert-manager
        - cilium
        - coredns
        - external-dns
        - kured
        - longhorn
        - metrics-server
        - victoria-logs
      loop_control:
        loop_var: postinstall
  roles:
    - cilium
    - coredns
    - cert-manager
    - external-dns
    - argo-cd
    - kured
    - longhorn
    - metrics-server
    - victoria-logs
    - victoria-metrics
  tags: charts
