---
- name: Cluster Validation
  hosts: cluster
  become: true
  gather_facts: true
  tasks:
    - name: Validate global settings
      ansible.builtin.include_role:
        apply:
          tags: '{{ validation }}'
        name: '{{ validation }}'
        tasks_from: validation
      loop:
        - cluster
        - k3s
        - argo-cd
        - cert-manager
        - cilium
        - coredns
        - external-dns
        - helm
        - kured
        - longhorn
        - metrics-server
        - victoria-logs
        - victoria-metrics
      loop_control:
        loop_var: validation
      tags: always
      when: (ansible_run_tags == ['all']) or (validation in ansible_run_tags)
