---
- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml
  any_errors_fatal: true

- name: Role Provisioning
  when: ansible_host in k3s_map.server.hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: '{{ k3s_vars.server.api.port }}'
        state: drained
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: '{{ longhorn_vars.kubernetes.helm.repository.org }}'
        repo_url: '{{ longhorn_vars.kubernetes.helm.repository.url }}'

    - name: Chart Setup
      run_once: true
      block:
        - name: Create backup credentials secret
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'credentials.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            wait: true
          when:
            - longhorn_vars.kubernetes.default_settings.backup.enabled is truthy
            - longhorn_vars.kubernetes.default_settings.backup.target[:4] | lower == 'cifs'
          no_log: true

        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            longhorn_postinstall: false

        - name: Install chart
          kubernetes.core.helm:
            chart_ref: '{{ longhorn_map.helm.chart.reference }}'
            chart_version: '{{ longhorn_vars.kubernetes.helm.chart.version }}'
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ longhorn_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ longhorn_vars.kubernetes.namespace }}'
            timeout: '{{ longhorn_map.helm.timeout }}'
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            create_namespace: true
            update_repo_cache: true
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed

        - name: Gateway Setup
          when: externaldns_vars.cloudflare.host.domain | lower != 'disabled'
          block:
            - name: Create gateway
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'gateway.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
                wait: true

            - name: Create insecure http route
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'http_route_insecure.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
                wait: true

            - name: Create secure http route
              kubernetes.core.k8s:
                definition: "{{ lookup('ansible.builtin.template', 'http_route_secure.j2') | from_yaml }}"
                kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
                wait: true
