---
- name: Set map fact
  ansible.builtin.set_fact:
    victoriametrics_map:
      credentials:
        grafana:
          secret: '{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-grafana-credentials'
      helm:
        chart:
          version: '{{ victoriametrics_vars.kubernetes.helm.chart.version[1:] }}'
        repository:
          - name: '{{ victoriametrics_vars.kubernetes.helm.repository.grafana.name }}'
            org: '{{ victoriametrics_vars.kubernetes.helm.repository.grafana.org }}'
            url: '{{ victoriametrics_vars.kubernetes.helm.repository.grafana.url }}'
          - name: '{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.name }}'
            org: '{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.org }}'
            url: '{{ victoriametrics_vars.kubernetes.helm.repository.prometheus.url }}'
          - name: '{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.name }}'
            org: '{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.org }}'
            url: '{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics.url }}'
        timeout: 10m0s
      ingress:
        alertmanager:
          annotations:
            cert-manager.io/cluster-issuer: '{{ externaldns_project.cloudflare.cluster.issuer }}'
          hostname: '{{ victoriametrics_vars.kubernetes.alertmanager.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}'
          name: alertmanager-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}
        class:
          name: cilium
        grafana:
          annotations:
            cert-manager.io/cluster-issuer: '{{ externaldns_project.cloudflare.cluster.issuer }}'
          hostname: '{{ victoriametrics_vars.kubernetes.grafana.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}'
          name: '{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-grafana'
        vmagent:
          annotations:
            cert-manager.io/cluster-issuer: '{{ externaldns_project.cloudflare.cluster.issuer }}'
          hostname: '{{ victoriametrics_vars.kubernetes.vmagent.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}'
          name: vmagent-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}
        vmalert:
          annotations:
            cert-manager.io/cluster-issuer: '{{ externaldns_project.cloudflare.cluster.issuer }}'
          hostname: '{{ victoriametrics_vars.kubernetes.vmalert.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}'
          name: vmalert-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}
        vmcluster:
          vminsert:
            annotations:
              cert-manager.io/cluster-issuer: '{{ externaldns_project.cloudflare.cluster.issuer }}'
            hostname: '{{ victoriametrics_vars.kubernetes.vmcluster.vminsert.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}'
            name: vminsert-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}
          vmselect:
            annotations:
              cert-manager.io/cluster-issuer: '{{ externaldns_project.cloudflare.cluster.issuer }}'
            hostname: '{{ victoriametrics_vars.kubernetes.vmcluster.vmselect.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}'
            name: vmselect-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}
          vmstorage:
            annotations:
              cert-manager.io/cluster-issuer: '{{ externaldns_project.cloudflare.cluster.issuer }}'
            hostname: '{{ victoriametrics_vars.kubernetes.vmcluster.vmstorage.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}'
            name: vmstorage-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}
        vmsingle:
          annotations:
            cert-manager.io/cluster-issuer: '{{ externaldns_project.cloudflare.cluster.issuer }}'
          hostname: '{{ victoriametrics_vars.kubernetes.vmsingle.ingress.subdomain }}.{{ externaldns_vars.cloudflare.host.domain }}'
          name: vmsingle-{{ victoriametrics_vars.kubernetes.helm.chart.alias }}-{{ victoriametrics_vars.kubernetes.helm.chart.name }}
      service:
        monitor:
          scrape:
            interval: 30s
            timeout: 25s
      spec:
        alertmanager:
          extra_args: {}
          extra_envs: []
        vmagent:
          extra_args: {}
          extra_envs:
            # Reduce CPU usage, in favor of memory usage
            - name: GOGC
              # Default value is `30`
              value: '60'
        vmalert:
          extra_args: {}
          extra_envs: []
        vmcluster:
          vminsert:
            extra_args: {}
            extra_envs: []
          vmselect:
            extra_args: {}
            extra_envs: []
          vmstorage:
            extra_args: {}
            extra_envs: []
        vmsingle:
          extra_args: {}
          extra_envs:
            # Reduce CPU usage, in favor of memory usage
            - name: GOGC
              # Default value is `30`
              value: '60'
  run_once: true

- name: Set project fact
  ansible.builtin.set_fact:
    victoriametrics_project:
      helm:
        chart:
          reference: '{{ victoriametrics_map.helm.repository[2].org }}/{{ victoriametrics_vars.kubernetes.helm.chart.name }}'
      tag: '{{ victoriametrics_vars.kubernetes.helm.chart.name }}-{{ victoriametrics_map.helm.chart.version }}'
      url: https://github.com/{{ victoriametrics_map.helm.repository[2].org }}/{{ victoriametrics_map.helm.repository[2].name }}/releases/tag
  run_once: true

- name: Set variables fact
  ansible.builtin.set_fact:
    victoriametrics_vars: '{{ victoriametrics_vars }}'
  run_once: true
