blank_issues_enabled: false
contact_links:
  - name: 📢 Community Discussions
    url: https://github.com/theepicsaxguy/k3s-cluster/discussions
    about: Please ask and answer general questions here.
