apiVersion: v2
name: victoria-metrics-k8s-stack
description: Documentation generator for victoria-metrics Ansible role
home: https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.36.2
appVersion: 1.0.0
