---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2204-ansible"
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
