---
- name: Set map fact
  ansible.builtin.set_fact:
    k3s_map:
      agent:
        ha: '{{ groups.agent | length > 2 }}'
      cluster:
        dns: 10.43.0.10
        label: default
      loadbalancer:
        hosts: '{{ groups.server[-2:] }}'
        password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=8) }}"
      node:
        directory:
          bin: /usr/local/bin
          config: /etc/rancher/k3s
          data: /var/lib/rancher/k3s
        tolerations:
          - key: node.cilium.io/agent-not-ready
            operator: Exists
            effect: NoExecute
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
      release:
        k3s:
          checksum: '{{ k3s_vars.release.k3s.checksum }}'
          url: 'https://github.com/{{ k3s_vars.release.k3s.repository.org }}/{{ k3s_vars.release.k3s.repository.name }}/releases'
        kubepug:
          checksum: '{{ k3s_vars.release.kubepug.name }}_{{ k3s_vars.release.kubepug.version[1:] }}_{{ k3s_vars.release.kubepug.checksum }}'
          url: 'https://github.com/{{ k3s_vars.release.kubepug.repository.org }}/{{ k3s_vars.release.kubepug.repository.name }}/releases'
      server:
        default_host: '{{ hostvars[groups.server[0]].ansible_hostname | default(groups.server[0]) }}'
        ha: '{{ groups.server | length > 2 }}'
        hosts: '{{ groups.server }}'
        non_ha: '{{ groups.server | length == 1 }}'
      service:
        name: "k3s{{ '-agent' if ansible_host not in groups.server }}"
  run_once: true

- name: Set map loadbalancer fact
  ansible.builtin.set_fact:
    k3s_map_loadbalancer:
      ips: "{{ k3s_map.loadbalancer.hosts | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
  when: ansible_host in k3s_map.loadbalancer.hosts

- name: Set map server fact
  ansible.builtin.set_fact:
    k3s_map_server:
      ips: "{{ k3s_map.server.hosts | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
  when: ansible_host in k3s_map.server.hosts

- name: Set node fact
  ansible.builtin.set_fact:
    k3s_node:
      ip: '{{ ansible_default_ipv4.address }}'
      kubelet:
        - arg: eviction-hard
          value: imagefs.available<15%,imagefs.inodesFree<5%,memory.available<500Mi,nodefs.available<10%,nodefs.inodesFree<5%
        - arg: eviction-max-pod-grace-period
          value: 60
        - arg: eviction-minimum-reclaim
          value: imagefs.available=15%,imagefs.inodesFree=5%,memory.available=500Mi,nodefs.available=10%,nodefs.inodesFree=5%
        - arg: eviction-soft
          value: imagefs.available<30%,imagefs.inodesFree<10%,memory.available<1Gi,nodefs.available<30%,nodefs.inodesFree<10%
        - arg: eviction-soft-grace-period
          value: imagefs.available=2m,imagefs.inodesFree=2m,memory.available=1m30s,nodefs.available=2m,nodefs.inodesFree=2m
        - arg: system-reserved
          value: cpu=1,ephemeral-storage=5Gi,memory=1Gi
      service: "{{ 'agent' if ansible_host not in k3s_map.server.hosts else 'server' }}"

- name: Set project fact
  ansible.builtin.set_fact:
    k3s_project:
      cluster:
        config: '{{ k3s_map.node.directory.config }}/config.yaml'
        kubeconfig: '{{ k3s_map.node.directory.config }}/{{ k3s_vars.release.k3s.name }}.yaml'
        registries: '{{ k3s_map.node.directory.config }}/registries.yaml'
        token: "{{ hostvars[k3s_map.server.default_host].k3s_project.cluster.token | default('') }}"
        tolerations: "{{ k3s_map.node.tolerations | select('search', 'control-plane') | default('') }}"
      node:
        binary: '{{ k3s_map.node.directory.bin }}/{{ k3s_vars.release.k3s.name }}'
      release:
        k3s:
          checksum: '{{ k3s_map.release.k3s.url }}/download/{{ k3s_vars.release.k3s.version }}/{{ k3s_map.release.k3s.checksum }}'
          file: '{{ k3s_map.release.k3s.url }}/download/{{ k3s_vars.release.k3s.version }}/{{ k3s_vars.release.k3s.file }}'
        kubepug:
          checksum: '{{ k3s_map.release.kubepug.url }}/download/{{ k3s_vars.release.kubepug.version }}/{{ k3s_map.release.kubepug.checksum }}'
          file: '{{ k3s_map.release.kubepug.url }}/download/{{ k3s_vars.release.kubepug.version }}/{{ k3s_vars.release.kubepug.file }}'
  run_once: true

- name: Set project kubelet arguments fact
  ansible.builtin.set_fact:
    k3s_project_kubelet_args: "{{ k3s_project_kubelet_args | default([]) | union(['='.join((kubelet.arg | string, kubelet.value | string))]) | sort }}"
  loop: '{{ k3s_node.kubelet }}'
  loop_control:
    loop_var: kubelet
  run_once: true

- name: Set project taints fact
  ansible.builtin.set_fact:
    k3s_project_taints: "{{ k3s_project_taints | default([]) | union([':'.join((taint.key | string, taint.effect | string))]) | sort }}"
  loop: '{{ k3s_map.node.tolerations }}'
  loop_control:
    loop_var: taint
  run_once: true

- name: Set resources fact
  ansible.builtin.set_fact:
    k3s_resources:
      node:
        kubelet:
          args: '{{ k3s_project_kubelet_args }}'
        taint:
          agent: "{{ k3s_project_taints | select('search', 'agent-not-ready') | default('') }}"
          server: "{{ k3s_project_taints | select('search', 'control-plane') | default('') }}"
  run_once: true

- name: Set variables fact
  ansible.builtin.set_fact:
    k3s_vars: '{{ k3s_vars }}'
  run_once: true
