---
- name: Role Facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Role Post-Install
  notify: Restart service
  when:
    - k3s_map.server.ha is truthy
    - ansible_host in k3s_map.server.hosts
  block:
    - name: Update server configuration postinstall fact
      ansible.builtin.set_fact:
        k3s_config_postinstall: true

    - name: Update server configuration file
      ansible.builtin.template:
        src: config.j2
        dest: '{{ k3s_project.cluster.config }}'
        owner: root
        group: root
        mode: '600'

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
