---
- name: Set map fact
  ansible.builtin.set_fact:
    coredns_map:
      config:
        # Extra configuration, applied outside of default zones block
        extra: {}
      helm:
        chart:
          reference: '{{ coredns_vars.kubernetes.helm.repository.org }}/{{ coredns_vars.kubernetes.helm.chart.name }}'
          version: '{{ coredns_vars.kubernetes.helm.chart.version[1:] }}'
        repository:
          name: '{{ coredns_vars.kubernetes.helm.repository.org }}/{{ coredns_vars.kubernetes.helm.repository.name }}'
          url: '{{ coredns_vars.kubernetes.helm.repository.url }}/{{ coredns_vars.kubernetes.helm.repository.name }}'
        timeout: 5m0s
      metrics:
        service:
          monitor:
            enabled: true
            scrape:
              # If `null`, default value is `victoriametrics_map.service.monitor.scrape.interval`
              interval: null
      zone:
        # Custom zone files, see https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/
        files: []
  run_once: true

- name: Set project fact
  ansible.builtin.set_fact:
    coredns_project:
      tag: '{{ coredns_vars.kubernetes.helm.chart.name }}-{{ coredns_map.helm.chart.version }}'
      url: https://github.com/{{ coredns_map.helm.repository.name }}/releases/tag
  run_once: true
