---
- name: Upgrade distribution packages
  ansible.builtin.apt:
    state: fixed
    upgrade: dist
    autoremove: true
    clean: true
    purge: true
    update_cache: true

# - name: Firmware Files Cleanup
#   when: cluster_vars.hardware.product | lower == 'raspberry pi'
#   block:
#     - name: Find firmware backup files
#       ansible.builtin.find:
#         path: /boot/firmware
#         patterns: '*.bak'
#         recurse: true
#       register: backup_files

#     - name: Purge firmware backup files
#       ansible.builtin.file:
#         path: '{{ item }}'
#         state: absent
#       loop: "{{ backup_files.files | map(attribute='path') | list }}"
