---
- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml
  any_errors_fatal: true

- name: Role Provisioning
  when: ansible_host in k3s_map.server.hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: '{{ k3s_vars.server.api.port }}'
        state: drained
        timeout: 30
      any_errors_fatal: true

    - name: Set checksums fact
      ansible.builtin.uri:
        url: '{{ certmanager_project.release.checksum }}'
        return_content: true
      register: checksums
      check_mode: false
      run_once: true

    - name: Set sha256 checksum fact
      ansible.builtin.set_fact:
        sha256_checksum: "{{ item.split(' ')[0] }}"
      loop: "{{ checksums.content.split('\n') }}"
      when: item | regex_search(certmanager_vars.release.file + '$')
      run_once: true

    - name: Install binary
      ansible.builtin.get_url:
        url: '{{ certmanager_project.release.file }}'
        checksum: sha256:{{ sha256_checksum }}
        dest: '{{ k3s_map.node.directory.bin }}/cmctl'
        owner: root
        group: root
        mode: '755'
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Create symlink
      ansible.builtin.file:
        path: '{{ k3s_map.node.directory.bin }}/kubectl-cert_manager'
        src: '{{ k3s_map.node.directory.bin }}/cmctl'
        state: link

    - name: Add repository
      kubernetes.core.helm_repository:
        name: '{{ certmanager_vars.kubernetes.helm.repository.org }}'
        repo_url: '{{ certmanager_vars.kubernetes.helm.repository.url }}'

    - name: Chart Setup
      run_once: true
      block:
        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            certmanager_postinstall: false

        - name: Install chart
          kubernetes.core.helm:
            chart_ref: '{{ certmanager_map.helm.chart.reference }}'
            chart_version: '{{ certmanager_vars.kubernetes.helm.chart.version }}'
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ certmanager_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ certmanager_vars.kubernetes.namespace }}'
            timeout: '{{ certmanager_map.helm.timeout }}'
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            create_namespace: true
            update_repo_cache: true
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed

        - name: Create self-signed cluster issuer
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'cluster_issuer.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            wait: true
