---
k3s_vars:
  architecture: amd64
  cluster:
    controlplane:
      tainted: true
    domain: kube.pc-tips.se
    kubeconfig:
      local: true
      path: "{{ lookup('ansible.builtin.env', 'HOME') + '/.kube' }}"
    service:
      host: 127.0.0.1
      port: 6444
    tls_san:
      - 10.25.150.10
      - kube.pc-tips.se
  network:
    interface: eth0
  release:
    k3s:
      checksum: "sha256sum-amd64.txt"
      file: "k3s-amd64"
      name: k3s
      repository:
        name: k3s
        org: k3s-io
      version: v1.31.6+k3s1
    kubepug:
      checksum: checksums.txt
      file: "kubepug_linux_amd64.tar.gz"
      name: kubepug
      repository:
        name: kubepug
        org: kubepug
      version: v1.7.1
  server:
    api:
      host: 10.25.150.10
      port: 6443
  service:
    debug: false
