# .github/workflows/ansible-dryrun.yml
name: Ansible Dry Run

on:
  pull_request:
    branches: ["main", "stable", "release/v*"]

jobs:
  dry-run:
    name: Run Ansible Playbook in Dry Mode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Execute Playbook in Check Mode
        run: ansible-playbook -i inventory ./provisioning.yaml --check

