# .github/workflows/inventory-validate.yml
name: Validate Ansible Inventory

on:
  pull_request:
    branches: ["main", "stable", "release/v*"]

jobs:
  inventory-check:
    name: Verify Ansible Inventory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Check Inventory Format
        run: ansible-inventory --list --yaml
