# .github/workflows/molecule-test.yml
name: Molecule Role Testing

on:
  pull_request:
    branches: ["main", "stable", "release/v*"]

jobs:
  molecule:
    name: Test Ansible Roles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule

      - name: Run Molecule Tests
        run: molecule test
